name: ngroup
description: "A newsgroup reader app."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  hooks_riverpod: ^2.4.10
  synchronized: ^3.1.0+1
  window_manager: ^0.3.8
  enough_mail:
    git:
      url: https://github.com/Kinwailo/enough_mail.git
      ref: main
  adaptive_dialog: ^2.0.0
  flex_color_scheme: ^7.3.1
  split_view: ^3.2.1
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_hooks: ^0.20.5
  badges: ^3.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5
  visibility_detector: ^0.4.0+2
  share_plus: ^7.2.2
  file_picker: ^6.1.1
  screenshot: ^2.1.0
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.1.0
  sanitize_filename: ^1.0.5
  linkify: ^5.0.0
  http: ^0.13.6
  metadata_fetch: ^0.4.1
  recase: ^4.1.0
  custom_refresh_indicator: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  icons_launcher: ^2.1.7
  package_rename_plus: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
